"""
Worldbuilding tables for settlement generation.
Geography, species, and challenge events.
"""

LOCATIONS: list[str] = [
    "Estuary",
    "Coastline",
    "Island",
    "Interior - Cross Roads",
    "Lake",
    "Interior - Road Stop",
    "Isolated Wilderness",
]

TERRAINS: list[str] = [
    "Mountains",
    "Forest",
    "Plains",
    "Desert",
    "Tundra",
    "Hills",
    "Valley",
    "Plateau",
    "Swamp",
    "Marsh",
]

# ── Species tables ────────────────────────────────────────────────────────────
# Named with source prefix so additional tables (homebrew, etc.) can be added later.

DND5_RACES: list[str] = [
    "Dragonborn", "Dwarf", "Elf", "Gnome", "Half-Elf", "Halfling", "Half-Orc",
    "Human", "Tiefling", "Genasi", "Goliath", "Bugbear", "Goblin", "Hobgoblin",
    "Kenku", "Kobold", "Lizardfolk", "Orc", "Shifter", "Warforged", "Gith",
    "Leonin", "Satyr", "Fairy", "Harengon", "Owlin", "Aarakocra", "Aasimar",
    "Firbolg", "Tabaxi", "Triton", "Yuan-ti", "Tortle", "Changeling", "Kalashtar",
    "Centaur", "Loxodon", "Minotaur", "Simic Hybrid", "Vedalken", "Verdan",
    "Locathah", "Grung",
]

# ── Challenge events ──────────────────────────────────────────────────────────
# Rolled each era during the Challenge phase. The GM localizes these to the
# settlement's geography, culture, and history.

CHALLENGE_EVENTS: list[str] = [
    "Plague of Insects",
    "Drought",
    "Raiders",
    "Disease",
    "Floods",
    "War",
    "Conquest",
    "Famine",
    "Fire",
    "Volcano",
    "Earthquake",
    "Tsunami",
    "Invasion",
    "Animal Migration",
    "Food shortage",
    "Overpopulation",
    "Poison",
    "Megafauna Extinction",
    "Exodus",
    "Rioting",
    "Mental Illness",
    "Hemophilia",
    "Structures collapse",
    "Frostbite",
    "Enslavement",
    "Dry well",
    "Mine collapse",
    "Mass suicide",
    "Civil war",
    "Sabotage",
    "Blockade / Blocked trade route",
    "Aberration",
    "Tiny natural beasts",
    "Small natural beasts",
    "Medium natural beasts",
    "Large natural beast",
    "Celestial",
    "Construct",
    "Dragon",
    "Elemental",
    "Fey",
    "Fiend",
    "Giant",
    "Bandits",
    "Monstrosity",
    "Ooze",
    "Plant creature",
    "Undead",
    "Neighboring city",
    "Coup",
    "Trade dispute",
    "Blight",
    "Extreme overgrowth",
    "Cursed",
    "Magical malady",
    "Forsaken by god(s)",
    "Treasures stolen",
    "Strange signs or symbols",
    "Kidnappings",
    "Magical tower appears",
    "Powerful artifact uncovered",
    "Ancient ruins discovered",
    "Dungeon / caves discovered",
    "Sinkhole",
    "Avalanche / rockslide",
    "Bounty hunter",
    "Mass memory loss",
    "Portal to another place",
    "Assassins",
    "Dreams",
    "Visions",
    "Lycanthropy",
    "Animated objects",
    "Storms",
    "Meteors",
    "Illusions",
    "Strange aging",
    "Invisible stalker",
    "Missionaries with strange beliefs",
    "Refugees",
    "Immigrants",
    "Racism",
    "Tax assessor",
    '"Rightful" heir',
    "Disturbing secrets made public",
    "City transported to another plane",
    "Heretical texts",
    "Fell from the sky",
    "Came up out of the ground",
    "Sterile / lack of virility",
    "Royal proclamation",
    "Swindled",
    "Leadership Summit",
    "Trial of the century",
    "Protests",
    "Lynchings",
    "Rogue police",
    "Thieves guild",
    "Apathy",
    "Narcolepsy",
    "Sudden climate shift",
    "Local fauna becomes aggressive",
    "Massive sinkhole opens",
    "New disease with strange symptoms",
    "Trading partner disappears",
    "Old mine reopens itself",
    "Strange markings appear overnight",
    "Elderly begin vanishing",
    "Underground tremors increase",
    "River changes course",
    "Long-dead language resurfaces",
    "Unseasonal storms",
    "Inexplicable freezing temperatures",
    "Visitors bring unfamiliar customs",
    "Unmarked graves are unearthed",
    "Children speak in riddles",
    "Dreams predict disaster",
    "Forgotten passage uncovered",
    "Sudden birthrate spike",
    "Animal migration changes",
    "Religious fervor surges",
    "Rain carries whispers",
    "Night sky displays unfamiliar stars",
    "Disguised outsiders infiltrate town",
    "Water turns murky and foul",
    "Lightning strikes repeatedly in same spot",
    "Dangerous plant spreads rapidly",
    "New species discovered",
    "Supplies rot overnight",
    "Tools crumble when used",
    "Bells ring with no cause",
    "People forget common knowledge",
    "Temporary madness affects population",
    "Inexplicable gravity fluctuations",
    "Statues begin to change position",
    "Warnings appear on walls",
    "Long-quiet volcano rumbles",
    "Smoke rises from the forest",
    "Familiar faces behave unusually",
    "Wind carries strange scents",
    "Ghostly figures seen at dusk",
    "Fish swarm land areas",
    "Trade goods vanish in transit",
    "Popular leader falls ill",
    "Unknown footprints found",
    "Important relic is stolen",
    "Law enforcement disappears",
    "Local well bubbles unnaturally",
    "No births recorded for a month",
    "Domestic animals flee",
    "Travelers report strange events",
    "Horizon glows unnaturally",
    "Written text decays",
    "Town clock runs backward",
    "Banners change color overnight",
    "Repeating echo in hills",
    "Unexpected eclipse",
    "Fire refuses to ignite",
    "Moon appears too large",
    "Distant horns heard at night",
    "Shadows stretch unnaturally",
    "Fog doesn't lift for days",
    "People fall asleep mid-task",
    "Music causes unrest",
    "Unusual birds gather",
    "Plants grow in patterns",
    "Sky filled with motes of light",
    "Stonework cracks in perfect lines",
    "Time feels disjointed",
    "Smoke that doesn't rise",
    "Stranger claims ownership of town",
    "Maps no longer match geography",
    "New building appears",
    "All livestock stops producing",
    "Drinking water glows faintly",
    "Insects swarm but don't bite",
    "Trade caravan overdue",
    "Religious site desecrated",
    "Local legend comes true",
    "Familiar terrain rearranged",
    "Reflections behave oddly",
    "Well-regarded person changes drastically",
    "Repeating dreams affect the community",
    "A strange song spreads",
    "Public records vanish",
    "Tools swap places overnight",
    "All colors slightly altered",
    "Impossible animal sighted",
    "Long-lost relative returns",
    "Entire day is missing from memory",
    "Communication with outside world fails",
    "Moon never rises",
    "Echoes repeat wrong words",
    "Spontaneous group dancing occurs",
    "Gold tarnishes instantly",
    "All fires burn blue",
    "Hair grows rapidly",
    "Unusual hatching found",
    "Unopened letters appear in mail",
    "A new faction rises from within, demanding independence",
    "A massive rift tears open in the earth near the city",
    "The sun fails to rise",
    "Crops grow, but are inedible",
    "A mysterious army gathers just outside the border",
    "All divine magic ceases",
    "The dead stop staying dead",
    "A powerful curse targets a specific bloodline",
    "Massive dome of energy cuts off part of the city",
    "All metal tools and weapons become brittle",
    "Rain doesn't stop for weeks — floodwaters rise",
    "A revered deity declares the settlement heretical",
    "The land becomes infertile overnight",
    "The city's leadership disappears without explanation",
    "All children fall into a magical slumber",
    "A disease spreads that only affects spellcasters",
    "A massive sinkhole swallows key infrastructure",
    "A once-loyal military force turns against its people",
    "A plague targets memory — no one recalls events",
    "The city's water turns acidic",
    "The ruling family is exposed as imposters",
    "All written records are wiped blank",
    "Magic surges create unpredictable effects",
    "One of the moons crashes to the earth",
    "Entire sections of the city vanish",
    "People begin transforming into another race",
    "The city is placed under magical quarantine",
    "A dragon claims the settlement as its lair",
    "An invading force demands religious conversion",
    "Food rots instantly when prepared",
    "The city's magic barrier begins to fail",
    "The stars rearrange into an ominous pattern",
    "Madness spreads from a single speaker's voice",
    "A massive storm never leaves the sky",
    "The sea pulls back — tides stop completely",
    "Earthquakes reveal a buried structure pulsing energy",
    "A prophecy demands mass sacrifice",
    "An old enemy claims a seat of power",
    "Every reflection shows a different reality",
    "A species of insects devours crops and homes",
    "The city's shadow separates and walks freely",
    "All music causes weeping and despair",
    "Entire race within the city begins vanishing",
    "Every newborn is marked with a mysterious rune",
    "Magical creatures flee the city, terrified",
    "A time loop traps the settlement",
    "An ancient weapon is unearthed — and activates",
    "Every oath ever made is undone",
    "Language begins breaking down",
    "The sky above the city tears open",
    "A massive celestial body approaches",
    "All birds fly away and do not return",
    "Earth elementals rise and demand land back",
    "The seasons stop cycling — winter never ends",
    "Dreams become shared and prophetic",
    "Monsters begin obeying an unknown signal",
    "The economy collapses due to arcane inflation",
    "The city's guardian spirit abandons them",
    "Nobles begin dying one by one",
    "A wave of suicides with no apparent cause",
    "Spires and towers begin crumbling simultaneously",
    "Roads become sentient and rearrange the city",
    "The sky over the city changes color and never reverts",
    "Something older than gods awakens beneath the city",
    "An entire generation falls ill with no cure",
    "All magic slowly drains toward one focal point",
    "A second sun appears and begins to burn",
    "A comet lingers too long in the sky",
    "All timekeeping devices run erratically",
    "Outsiders claim the settlement is cursed",
    "Loyal animals begin turning on their owners",
    "Dreams start predicting crimes before they happen",
    "A revered artifact is revealed to be a lie",
    "Food begins vanishing from storage",
    "Faction leaders begin turning to stone",
    "All maps change overnight",
    "Non-humanoid creatures begin forming governments",
    "Plague leaves survivors with permanent magical mutations",
    "Gravity fluctuates wildly across the city",
    "A new, intelligent species demands territory",
    "The stars go out",
    "The settlement appears on every map, in every realm",
    "Outsiders believe the city holds a cosmic key",
    "A voice is heard in all minds, giving commands",
    "All weather patterns freeze in place",
    "The rivers stop moving",
    "The gods fall silent during prayers",
    "Strange spores drift through the air",
    "The foundations of the city are sinking",
    "Every spell comes with a price in blood",
    "Ancient beings return, expecting tribute",
    "The city begins sliding into the sea",
    "Everyone born in a certain year vanishes",
    "A monolith rises in the city square overnight",
    "The moon appears cracked",
    "All illusions become real",
    "The past begins replacing the present",
    "Every reflection shows a coming apocalypse",
    "The wind speaks secrets",
    "Every pet in the city turns hostile at once",
    "The sun rises in the west",
    "A vast forest sprouts overnight where none stood",
    "A second city appears, identical to the first",
    "The air itself becomes flammable",
    "Every living creature casts a second, moving shadow",
    "Lightning strikes the same tower every hour",
    "All glass begins to hum and shatter",
    "A ghostly version of the city overlaps it at night",
    "Weather happens in reverse: rain rises, snow falls upward",
    "No sound can be made within city walls",
    "A voice in the sky begins reciting the names of residents",
    "The ground pulses like a heartbeat",
    "The sea turns to fog",
    "The city's colors desaturate one by one",
    "Gravity weakens — residents begin drifting",
    "Every coin melts into a different material",
    "A ring of floating stones appears around the city",
    "Giant footprints appear — no giant in sight",
    "Time slows to a crawl within the market",
    "Day and night cycle every hour",
    "All metal begins singing when touched",
    "Residents grow younger over time",
    "Everyone dreams of the same place — then it appears",
    "Animals become able to speak, but refuse to explain",
    "The city is encased in a globe of perfect stillness",
    "All ships sail inland without wind",
    "New stars appear and arrange into sigils",
    "Every mirror shows someone else's life",
    "A river of flame erupts through the farmland",
    "Everyone hears a countdown — but no source",
    "A colossal statue walks out of the mountains",
    "People swap identities randomly each dawn",
    "Insects form moving glyphs across the city",
    "A chorus of invisible children sings each morning",
    "Fire burns, but produces no heat or light",
    "The city's name is erased from all memory",
    "A language no one knows is suddenly spoken fluently",
    "Everyone sees the same stranger in different forms",
    "A voice narrates everything that happens — wrongly",
    "The moon begins to sing",
    "Every building slowly rotates in place",
    "All birds fly in a perfect circle over the city",
    "The sky peels back to reveal a painted dome",
    "Every newborn has a glowing birthmark",
    "The wind forms words in the sand",
    "Roads stretch and twist when unobserved",
    "Music causes hallucinations of other lives",
    "Ice begins growing from the shadows",
    "Everyone hears their own voice crying out",
    "Residents begin transforming into crystal",
    "A stairwell to nowhere becomes a pilgrimage site",
    "Shadows form into hands at dusk",
    "All eyes change color simultaneously",
    "A mountain appears where none existed",
    "Everyone feels watched — but there are no observers",
    "New laws appear carved in stone each morning",
    "The city rises ten feet overnight",
    "Time loops — only some people notice",
    "Every story becomes true for a day",
    "Beasts from children's books begin appearing",
    "A garden grows on every rooftop",
    "Wounds vanish, but pain remains",
    "Rain paints prophetic murals",
    "Bridges vanish when crossed",
    "Fog shows visions of alternate timelines",
    "Fire spreads but consumes no fuel",
    "Graves dig themselves open",
    "Echoes speak different words than were said",
    "Dreams replay recent events with changed outcomes",
    "All magic works perfectly — but leaves a mark",
    "People grow wings that don't function",
    "A giant face appears in the mountainside",
    "Everyone begins writing the same phrase",
    "Stars blink in a pattern — then stop",
    "The horizon folds in like paper",
    "The wind carries old songs and forgotten prayers",
    "A storm of dust, bones, and feathers approaches",
    "The dead begin writing letters",
    "The city's reflection floats above it in the sky",
    "Sound becomes visible",
    "A new day of the week is added — but only some observe it",
    "Rivers flow with memories",
    "Time fractures — people live different lives simultaneously",
    "Unseen creatures move through crowded spaces",
    "Doors lead to unexpected versions of their rooms",
    "Maps of the city become mazes",
    "Dreams of a perfect city cause unrest",
    "Magic changes color and properties",
    "A sunken part of the city rises again",
    "A second heartbeat is heard in everyone",
    "Water glows with the past",
    "Stars weep fire for an hour",
    "Trees bend toward a single direction — always",
    "Sounds echo from events that haven't happened",
    "The dead walk silently at dawn",
    "Roads bleed where they cross",
    "People forget how to read — but not speak",
    "Animals build structures mimicking the city",
    "The sky opens like an eye, then closes",
    "Gravity reverses one object per day",
]

# ── Boons ─────────────────────────────────────────────────────────────────────
# Awarded on successful challenge resolution. The GM localizes and narrates.

BOON_TABLE: list[str] = [
    "Magic Armor",
    "Magic Potion Formula",
    "Magic Ring",
    "Magic Rod",
    "Magic Staff",
    "Magic Wand",
    "Magic Weapon",
    "Wondrous Item",
    "Extraordinary Temple",
    "Extraordinary Fortifications",
    "Masterwork Art",
    "Masterwork Architecture",
    "Masterwork Clothing",
    "Elemental Patron",
    "Masterwork Writings",
    "Masterwork Music",
    "Masterwork Tools",
    "Masterwork Glass",
    "Masterwork Ships or Wagons",
    "Masterwork Pottery",
    "Masterwork Jewelry",
    "Masterwork Carpentry",
    "Masterwork Clockworks",
    "Masterwork Gardens",
    "Extraordinary Palace / State Building",
    "Domesticated Medium Beasts",
    "Domesticated Large Beasts",
    "Domesticated Huge Beasts",
    "Domesticated Small Magical Beasts",
    "Domesticated Medium Magical Beast",
    "Domesticated Large Magical Beasts",
    "Extraordinary Roads",
    "Extraordinary Irrigation",
    "Extraordinary Docks",
    "Extraordinary Bridges",
    "Extraordinary Sewers",
    "Extraordinary Farming Techniques",
    "Extraordinary Animal Husbandry",
    "Extraordinary Marketplace",
    "Ally Settlement at an Estuary",
    "Ally Settlement at a Coastline",
    "Ally Settlement on an Island",
    "Ally Settlement on a River",
    "Ally Settlement on a Lake",
    "Ally Settlement at a Cross Roads",
    "Ally Settlement at a Road Stop",
    "Ally Settlement in Remote Wilderness",
    "Lighthouse / Beacons",
    "Extraordinary Tower",
    "Extraordinary Granary",
    "Extraordinary Stockyards",
    "Generation of peace (skip next challenge)",
    "Extraordinary Necropolis",
    "Political Process or Property Law",
    "Spiritual Enlightenment",
    "Personality Quirk or Social Contract",
    "Symbol of Values",
    "Production Technique or Elemental Discovery",
    "Merger with neighboring town",
    "Geographical Discovery",
    "Historical Discovery",
    "Magical Discovery",
    "Engineering Discovery",
    "Scholarly Discovery",
    "Astrological Discovery",
    "Linguistic Discovery",
    "Social Discovery",
    "Scientific Discovery",
    "Spiritual Discovery",
    "Calendrical Discovery",
    "Leadership Discovery",
    "Labor Discovery",
    "Extraordinary Library",
    "Extraordinary Housing",
    "Natural Discovery",
    "Magical Bloodline",
    "Mining Discovery",
    "Trade Route Discovery",
    "Manufacturing Discovery",
    "Elemental Discovery",
    "Production Technique Discovery",
    "Trade Partner at an Estuary",
    "Trade Partner at a Coastline",
    "Trade Partner on an Island",
    "Trade Partner on a River",
    "Trade Partner on a Lake",
    "Trade Partner at a Cross Roads",
    "Trade Partner at a Road Stop",
    "Trade Partner in Remote Wilderness",
    "Archfey Patron",
    "Celestial Patron",
    "Fiend Patron",
    "Great Old One Patron",
    "Genie Patron",
    "Undying Patron",
    "Hexblade Patron",
    "Fathomless Patron",
    "Physical Evolutionary Trait",
    "Magical Evolutionary Trait",
    "TWO boons! (reroll twice)",
]
